// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: proto/lampada.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LampadaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
}

func (x *LampadaRequest) Reset() {
	*x = LampadaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lampada_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LampadaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LampadaRequest) ProtoMessage() {}

func (x *LampadaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lampada_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LampadaRequest.ProtoReflect.Descriptor instead.
func (*LampadaRequest) Descriptor() ([]byte, []int) {
	return file_proto_lampada_proto_rawDescGZIP(), []int{0}
}

func (x *LampadaRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome                string  `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Tipo                string  `protobuf:"bytes,2,opt,name=Tipo,proto3" json:"Tipo,omitempty"`
	Power               bool    `protobuf:"varint,3,opt,name=Power,proto3" json:"Power,omitempty"`
	Status              string  `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	IntensidadeLuminosa float32 `protobuf:"fixed32,5,opt,name=IntensidadeLuminosa,proto3" json:"IntensidadeLuminosa,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lampada_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lampada_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_lampada_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Response) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Response) GetPower() bool {
	if x != nil {
		return x.Power
	}
	return false
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Response) GetIntensidadeLuminosa() float32 {
	if x != nil {
		return x.IntensidadeLuminosa
	}
	return 0
}

type ArCondicionadoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
}

func (x *ArCondicionadoRequest) Reset() {
	*x = ArCondicionadoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lampada_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArCondicionadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArCondicionadoRequest) ProtoMessage() {}

func (x *ArCondicionadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lampada_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArCondicionadoRequest.ProtoReflect.Descriptor instead.
func (*ArCondicionadoRequest) Descriptor() ([]byte, []int) {
	return file_proto_lampada_proto_rawDescGZIP(), []int{2}
}

func (x *ArCondicionadoRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type ArCondicionadoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome                string  `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Tipo                string  `protobuf:"bytes,2,opt,name=Tipo,proto3" json:"Tipo,omitempty"`
	Power               bool    `protobuf:"varint,3,opt,name=Power,proto3" json:"Power,omitempty"`
	Status              string  `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	IntensidadeLuminosa float32 `protobuf:"fixed32,5,opt,name=IntensidadeLuminosa,proto3" json:"IntensidadeLuminosa,omitempty"`
}

func (x *ArCondicionadoResponse) Reset() {
	*x = ArCondicionadoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lampada_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArCondicionadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArCondicionadoResponse) ProtoMessage() {}

func (x *ArCondicionadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lampada_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArCondicionadoResponse.ProtoReflect.Descriptor instead.
func (*ArCondicionadoResponse) Descriptor() ([]byte, []int) {
	return file_proto_lampada_proto_rawDescGZIP(), []int{3}
}

func (x *ArCondicionadoResponse) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *ArCondicionadoResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ArCondicionadoResponse) GetPower() bool {
	if x != nil {
		return x.Power
	}
	return false
}

func (x *ArCondicionadoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ArCondicionadoResponse) GetIntensidadeLuminosa() float32 {
	if x != nil {
		return x.IntensidadeLuminosa
	}
	return 0
}

type ControleDeIncendioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
}

func (x *ControleDeIncendioRequest) Reset() {
	*x = ControleDeIncendioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lampada_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControleDeIncendioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControleDeIncendioRequest) ProtoMessage() {}

func (x *ControleDeIncendioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lampada_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControleDeIncendioRequest.ProtoReflect.Descriptor instead.
func (*ControleDeIncendioRequest) Descriptor() ([]byte, []int) {
	return file_proto_lampada_proto_rawDescGZIP(), []int{4}
}

func (x *ControleDeIncendioRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

var File_proto_lampada_proto protoreflect.FileDescriptor

var file_proto_lampada_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x61, 0x64, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x4c, 0x61, 0x6d, 0x70, 0x61, 0x64, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x70, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30,
	0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x64, 0x61, 0x64, 0x65, 0x4c, 0x75, 0x6d,
	0x69, 0x6e, 0x6f, 0x73, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x13, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x64, 0x61, 0x64, 0x65, 0x4c, 0x75, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x61,
	0x22, 0x2b, 0x0a, 0x15, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x61,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x22, 0xa0, 0x01,
	0x0a, 0x16, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x61, 0x64, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x70, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30,
	0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x64, 0x61, 0x64, 0x65, 0x4c, 0x75, 0x6d,
	0x69, 0x6e, 0x6f, 0x73, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x13, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x64, 0x61, 0x64, 0x65, 0x4c, 0x75, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x61,
	0x22, 0x2f, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x49, 0x6e,
	0x63, 0x65, 0x6e, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d,
	0x65, 0x32, 0x68, 0x0a, 0x07, 0x4c, 0x61, 0x6d, 0x70, 0x61, 0x64, 0x61, 0x12, 0x2c, 0x0a, 0x0c,
	0x4c, 0x69, 0x67, 0x61, 0x72, 0x4c, 0x61, 0x6d, 0x70, 0x61, 0x64, 0x61, 0x12, 0x0f, 0x2e, 0x4c,
	0x61, 0x6d, 0x70, 0x61, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0f, 0x44, 0x65,
	0x73, 0x6c, 0x69, 0x67, 0x61, 0x72, 0x4c, 0x61, 0x6d, 0x70, 0x61, 0x64, 0x61, 0x12, 0x0f, 0x2e,
	0x4c, 0x61, 0x6d, 0x70, 0x61, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x8b, 0x01, 0x0a, 0x0e,
	0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x61, 0x64, 0x6f, 0x12, 0x3a,
	0x0a, 0x13, 0x4c, 0x69, 0x67, 0x61, 0x72, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69,
	0x6f, 0x6e, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x2e, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63,
	0x69, 0x6f, 0x6e, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x16, 0x44, 0x65,
	0x73, 0x6c, 0x69, 0x67, 0x61, 0x72, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f,
	0x6e, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x2e, 0x41, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69,
	0x6f, 0x6e, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x9f, 0x01, 0x0a, 0x12, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x49, 0x6e, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6f,
	0x12, 0x42, 0x0a, 0x17, 0x4c, 0x69, 0x67, 0x61, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x65, 0x44, 0x65, 0x49, 0x6e, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6f, 0x12, 0x1a, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x49, 0x6e, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x1a, 0x44, 0x65, 0x73, 0x6c, 0x69, 0x67, 0x61, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x49, 0x6e, 0x63, 0x65, 0x6e, 0x64,
	0x69, 0x6f, 0x12, 0x1a, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x49,
	0x6e, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lampada_proto_rawDescOnce sync.Once
	file_proto_lampada_proto_rawDescData = file_proto_lampada_proto_rawDesc
)

func file_proto_lampada_proto_rawDescGZIP() []byte {
	file_proto_lampada_proto_rawDescOnce.Do(func() {
		file_proto_lampada_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lampada_proto_rawDescData)
	})
	return file_proto_lampada_proto_rawDescData
}

var file_proto_lampada_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_lampada_proto_goTypes = []interface{}{
	(*LampadaRequest)(nil),            // 0: LampadaRequest
	(*Response)(nil),                  // 1: Response
	(*ArCondicionadoRequest)(nil),     // 2: ArCondicionadoRequest
	(*ArCondicionadoResponse)(nil),    // 3: ArCondicionadoResponse
	(*ControleDeIncendioRequest)(nil), // 4: ControleDeIncendioRequest
}
var file_proto_lampada_proto_depIdxs = []int32{
	0, // 0: Lampada.LigarLampada:input_type -> LampadaRequest
	0, // 1: Lampada.DesligarLampada:input_type -> LampadaRequest
	2, // 2: ArCondicionado.LigarArCondicionado:input_type -> ArCondicionadoRequest
	2, // 3: ArCondicionado.DesligarArCondicionado:input_type -> ArCondicionadoRequest
	4, // 4: ControleDeIncendio.LigarControleDeIncendio:input_type -> ControleDeIncendioRequest
	4, // 5: ControleDeIncendio.DesligarControleDeIncendio:input_type -> ControleDeIncendioRequest
	1, // 6: Lampada.LigarLampada:output_type -> Response
	1, // 7: Lampada.DesligarLampada:output_type -> Response
	1, // 8: ArCondicionado.LigarArCondicionado:output_type -> Response
	1, // 9: ArCondicionado.DesligarArCondicionado:output_type -> Response
	1, // 10: ControleDeIncendio.LigarControleDeIncendio:output_type -> Response
	1, // 11: ControleDeIncendio.DesligarControleDeIncendio:output_type -> Response
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lampada_proto_init() }
func file_proto_lampada_proto_init() {
	if File_proto_lampada_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lampada_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LampadaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lampada_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lampada_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArCondicionadoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lampada_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArCondicionadoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lampada_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControleDeIncendioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lampada_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_lampada_proto_goTypes,
		DependencyIndexes: file_proto_lampada_proto_depIdxs,
		MessageInfos:      file_proto_lampada_proto_msgTypes,
	}.Build()
	File_proto_lampada_proto = out.File
	file_proto_lampada_proto_rawDesc = nil
	file_proto_lampada_proto_goTypes = nil
	file_proto_lampada_proto_depIdxs = nil
}
